export const PRODUCT_LIST_REQUEST ='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCESS='PRODUCT_LIST_SUCESS';
export const PRODUCT_LIST_FAIL ='PRODUCT_LIST_FAIL';



export const PRODUCT_DEATIALS_REQUEST ='PRODUCT_DEATIALS_REQUEST';
export const PRODUCT_DEATIALS_SUCESS='PRODUCT_DEATIALS_SUCESS';
export const PRODUCT_DEATIALS_FAIL ='PRODUCT_DEATIALS_FAIL';